SELECT
   REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REPLACE(LOWER(product.label), ' ', '-'), '[éèê]', 'e'), '[@àâ]', 'a'), '[?!:;,./€#$@()_'']','' ) AS "Handle",
   CONCAT(CONCAT('"', CONCAT(product.label)),'"') AS "Title",
   product.description AS "Body (HTML)",
   '' AS "Vendor",
   '' AS "Product Category",
   '' AS "Type",
   CONCAT(CONCAT('"', GROUP_CONCAT(categorie.label)),'"') AS "Tags",
   'TRUE' AS "Published",
   '' AS "Option1 Name",
   '' AS "Option1 Value",
   '' AS "Option2 Name",
   '' AS "Option2 Value",
   '' AS "Option3 Name",
   '' AS "Option3 Value",
   '' AS "Variant SKU",
   '0.0' AS "Variant Grams",
   'shopify' AS "Variant Inventory Tracker",
   '0' AS "Variant Inventory Qty",
   'deny' AS "Variant Inventory Policy",
   'manual' AS "Variant Fulfillment Service",
   ROUND(product.price_ttc, 2) AS "Variant Price",
   '' AS "Variant Compare At Price",
   '' AS "Variant Requires Shipping",
   'true' AS "Variant Taxable",
   '' AS "Variant Barcode",
   '' AS "Image Src",
   '' AS "Image Position",
   '' AS "Image Alt Text",
   'FALSE' AS "Gift Card",
   '' AS "SEO Title",
   '' AS "SEO Description",
   '' AS "Google Shopping / Google Product Category",
   '' AS "Google Shopping / Gender",
   '' AS "Google Shopping / Age Group",
   '' AS "Google Shopping / MPN",
   '' AS "Google Shopping / AdWords Grouping",
   '' AS "Google Shopping / AdWords Labels",
   '' AS "Google Shopping / Condition",
   '' AS "Google Shopping / Custom Product",
   '' AS "Google Shopping / Custom Label 0",
   '' AS "Google Shopping / Custom Label 1",
   '' AS "Google Shopping / Custom Label 2",
   '' AS "Google Shopping / Custom Label 3",
   '' AS "Google Shopping / Custom Label 4",
   '' AS "Variant Image",
   'kg' AS "Variant Weight Unit",
   '' AS "Variant Tax Code",
   '' AS "Cost per item",
   '' AS "Price / International",
   '' AS "Compare At Price / International",
   'draft' as "STATUS"
FROM dolibarr.llx_product product
LEFT JOIN dolibarr.llx_categorie_product categorie_product ON (categorie_product.fk_product = product.rowid)
INNER JOIN dolibarr.llx_categorie categorie ON (categorie.rowid = categorie_product.fk_categorie)
WHERE product.tosell = 1
GROUP BY
    product.label
;